plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-berry.cjs

packageExtensions:
  "styled-components@*":
    peerDependencies:
      "react-is": "*"
  "next-optimized-images@*":
    peerDependencies:
      "webpack": "*"
  "reakit-warning@*":
    peerDependencies:
      "react-dom": "^16.8.0"