plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-berry.cjs

packageExtensions:
  "styled-components@*":
    peerDependencies:
      "react-is": "*"
  "next-optimized-images@*":
    peerDependencies:
      "webpack": "*"
  "react-apollo@*":
    peerDependencies:
      "apollo-utilities": "^1.3.2"
      "apollo-cache": "^1.3.2"
      "apollo-link": "^1.2.12"
  "@apollo/react-hoc@*":
    peerDependencies:
      "apollo-utilities": "^1.3.2"
      "apollo-cache": "^1.3.2"
      "apollo-link": "^1.2.12"
  "@apollo/react-hooks@*":
    peerDependencies:
      "apollo-utilities": "^1.3.2"
  "@apollo/react-ssr@*":
    peerDependencies:
      "apollo-client": "^2.6.4"
      "apollo-utilities": "^1.3.2"
      "graphql": "^14.3.1"
  "reakit-warning@*":
    peerDependencies:
      "react-dom": "^16.8.0"